// ── Blog post content — written by Terry, Chief Editor, SouthportGuide.co.uk ──
// Terry is a 41-year-old Southport local living in Churchtown with his wife,
// four kids, and a bulldog called Frank.

export type ContentBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "callout"; emoji: string; text: string }
  | { type: "quote"; text: string; attr?: string }
  | { type: "hr" };

export const BLOG_CONTENT: Record<string, ContentBlock[]> = {

  "best-restaurants-southport-2026": [
    { type: "p", text: "I've lived in Southport my whole life. Forty-one years. I've eaten in most of the restaurants in this town — some of them multiple times a week when the kids were small and we were too tired to cook. So when I say this is the honest guide, I mean it. No paid placements, no favours. Just the places I'd send my parents to if they were visiting." },
    { type: "h2", text: "The ones that keep delivering" },
    { type: "p", text: "Hickory's Smokehouse on the waterfront is a crowd-pleaser for a reason. American BBQ, big portions, kids eat free on certain nights. It's always busy, but the kitchen handles it well. Book ahead — I've made the mistake of walking in on a Saturday and waiting an hour. Worth it, but book ahead." },
    { type: "p", text: "The Swan Restaurant in Churchtown is where I take my parents when they visit. It's proper food, properly cooked. The setting alone — right on the edge of Churchtown village — makes it worth the detour. If you haven't been to Churchtown at all, go. It's the bit of Southport that surprises people." },
    { type: "h2", text: "Fine dining on Lord Street" },
    { type: "p", text: "Lord Street has a decent range of restaurants under its famous glass canopies. Volare is the Italian you'll hear locals mention — it's been there forever, and it's consistent. Not flash, but reliable pasta and good wine. Perfect if you want a proper sit-down meal without drama." },
    { type: "p", text: "For something a bit more special, there are a handful of independent restaurants along the boulevard that change their menus seasonally. Worth checking what's on before you visit. Southport's dining scene is quietly improving — the kind of thing you only notice if you've been watching it for decades." },
    { type: "h2", text: "For families" },
    { type: "p", text: "Four kids means I know every family-friendly restaurant in this town intimately. The chains on Ocean Plaza do the job when you just need everyone fed without incident. But if you want something with more character, Hickory's handles kids better than most." },
    { type: "p", text: "Southport Market on Market Street is worth knowing about — street food stalls under one roof, different cuisines, buzzy atmosphere. If the kids can't agree on what to eat (and mine never can), it's perfect. Someone gets pizza, someone gets a burger, everyone's happy." },
    { type: "h2", text: "Hidden gems worth the detour" },
    { type: "p", text: "Birkdale village has a handful of independent restaurants that visitors rarely find. It's a ten-minute drive from the town centre, but it feels worlds away. A quieter, more residential feel, with some genuinely good food. Worth exploring if you've already ticked off the Lord Street options." },
    { type: "callout", emoji: "📍", text: "Always check opening times before you go — Southport restaurants sometimes keep shorter winter hours. A quick phone call saves a wasted journey." },
    { type: "h2", text: "The honest takeaway" },
    { type: "p", text: "Southport's restaurant scene isn't London. We're not trying to be. But there's genuinely good food here — fresh fish close to the coast, solid pub food, some standout independents that deserve more recognition than they get. If you're visiting for The Open or MLEC, make time to eat properly. You won't regret it." },
  ],

  "dog-friendly-pubs-southport": [
    { type: "p", text: "Frank is a bulldog. He's three years old, weighs about the same as my eight-year-old, and has opinions about everything — including which pubs deserve his presence. Over the past couple of years, he's visited most of the dog-friendly pubs in Southport and surrounding areas. This is his guide, as dictated to me." },
    { type: "h2", text: "What actually makes a pub dog-friendly" },
    { type: "p", text: "There's 'dogs welcome' and then there's genuinely dog-friendly. The difference matters if you've got a big dog who needs space, or a dog who needs to settle before he's comfortable." },
    { type: "ul", items: [
      "Water bowl available without asking",
      "Enough space between tables to manoeuvre without drama",
      "Staff who acknowledge the dog without making it weird",
      "Beer garden (for warmer days, and for dogs who need a leg stretch)",
      "Treats at the bar — a bonus, not a requirement"
    ]},
    { type: "h2", text: "The Hesketh Arms, Churchtown" },
    { type: "p", text: "This is Frank's local. It's a proper traditional pub — low ceilings, real ale, a roaring fire in winter. Dogs are welcomed warmly, there's a water bowl by the bar, and the beer garden is large and flat enough for Frank to lumber around without incident." },
    { type: "p", text: "The Hesketh is also just a genuinely good pub. Food is solid pub grub, service is friendly, and it fills up with regulars at weekends. If you're staying in Southport and want to experience a real local, this is it." },
    { type: "h2", text: "Birkdale and Ainsdale options" },
    { type: "p", text: "The Bold Hotel in Birkdale has a bar area that welcomes dogs. It's a more upmarket setting — the kind of place you bring Frank when you want to look like you have your life together. Staff are unfailingly polite to both of us." },
    { type: "p", text: "Further out toward Ainsdale, there are a couple of pubs along the coast road that are happy to accommodate dogs. Worth calling ahead to confirm, especially at weekends when it gets busy." },
    { type: "h2", text: "Town centre options" },
    { type: "p", text: "Town centre pubs are more hit and miss. The Ship and Anchor is reliably dog-friendly and has the rock pub atmosphere to prove it. The Windmill on the edge of town is another good option — bigger beer garden, slightly less chaotic on weekends." },
    { type: "callout", emoji: "🐾", text: "Always call ahead on busy event weekends. The Open, the Flower Show, and the Comedy Festival all draw big crowds, and some pubs temporarily restrict dogs in certain areas." },
    { type: "h2", text: "Frank's verdict" },
    { type: "p", text: "If Frank could write, he'd tell you The Hesketh Arms is unbeatable. He'd also tell you that any pub that brings treats unprompted gets an extra star. He has standards, despite appearances." },
  ],

  "where-to-stay-open-championship-2026": [
    { type: "p", text: "The Open Championship at Royal Birkdale runs 12–19 July 2026. If you haven't booked accommodation yet, stop reading and go book something. I'm serious. I write a local guide for a living and even I'm worried about whether there'll be anything left by the time you read this." },
    { type: "h2", text: "How close do you need to be?" },
    { type: "p", text: "Royal Birkdale is in Birkdale, which is the southern end of Southport — about 2 miles from the town centre. You don't need to stay on the doorstep. A hotel in town centre is completely manageable, especially if you use the shuttle buses that will be running during Open week." },
    { type: "h2", text: "The Grand, Lord Street" },
    { type: "p", text: "The Grand is Southport's flagship hotel — a beautiful Victorian building on Lord Street with proper grandeur. It books out months in advance for Open week. If you're lucky enough to have a room, you've landed well. It's a short taxi or shuttle from Birkdale, and there's something fitting about staying at The Grand for an event as prestigious as The Open." },
    { type: "h2", text: "The Bold Hotel, Birkdale" },
    { type: "p", text: "The Bold is the closest quality hotel to Royal Birkdale. It's a boutique hotel with a strong reputation — individually styled rooms, good bar, and the kind of place that takes pride in getting the details right. Birkdale village itself is pleasant to wander in the evenings. This is probably the most sought-after accommodation for Open week." },
    { type: "h2", text: "Self-catering for groups" },
    { type: "p", text: "If you're coming as a group of four or more, self-catering is the smart move. There are holiday apartments and houses around Southport that can accommodate groups more affordably than booking multiple hotel rooms. Search early. Things that are available in March won't be available in June." },
    { type: "h2", text: "What about Formby and Ormskirk?" },
    { type: "p", text: "If Southport is fully booked, Formby is 20 minutes south by car and has some good accommodation options. Ormskirk is 30 minutes east. Both are manageable commutes for Open week, especially if you plan around the shuttle services." },
    { type: "callout", emoji: "⚠️", text: "Don't rely on last-minute availability. The Open at Royal Birkdale is a once-in-several-years event. Southport fills up entirely. Book now." },
    { type: "h2", text: "The local's view on Open week" },
    { type: "p", text: "Open week is brilliant and chaotic in equal measure. Restaurants are packed, parking is a nightmare, and the atmosphere is electric. My advice: book a good hotel, get a shuttle bus pass sorted, and don't try to drive anywhere near the course. Walk instead. Enjoy it. There's nothing quite like having The Open on your doorstep." },
  ],

  "best-bnbs-southport": [
    { type: "p", text: "I'll be honest — I'm a B&B man at heart. When I travel, I'd rather have a proper breakfast made by someone who cares than a buffet of lukewarm scrambled eggs in a Premier Inn. Southport has some genuinely good B&Bs and guest houses. They don't get the press the hotels do, but they should." },
    { type: "h2", text: "What Southport B&Bs do well" },
    { type: "p", text: "The best Southport guest houses tend to be Victorian townhouses — substantial buildings with high ceilings, proper rooms, and often a breakfast room that feels like it belongs to somebody's life rather than a hotel business. That's the experience worth seeking out." },
    { type: "ul", items: [
      "Proper cooked breakfasts, often with local produce",
      "Hosts who actually know the town and give genuine recommendations",
      "More character per pound than chain hotels",
      "Often in quieter residential areas, away from weekend noise"
    ]},
    { type: "h2", text: "Birkdale and the south end" },
    { type: "p", text: "Birkdale village has a cluster of guest houses that attract golfers visiting Royal Birkdale. They're used to early checkouts, kit storage, and guests who want a hearty breakfast before 8am. Good value, and the village itself is lovely to wander the night before." },
    { type: "h2", text: "Town centre and Lord Street area" },
    { type: "p", text: "Guest houses close to Lord Street put you within walking distance of most restaurants, bars, and the train station. Handy if you're visiting without a car. Check reviews carefully — the good ones have genuinely enthusiastic hosts, the less good ones have let standards slip a bit." },
    { type: "callout", emoji: "💡", text: "Check the review dates. Southport was affected by flooding in 2023, and some properties went through a difficult period. Anything with consistent positive reviews from the last 12 months is the reliable benchmark." },
    { type: "h2", text: "What to ask before booking" },
    { type: "ul", items: [
      "Is breakfast included, and what does it include?",
      "Is there secure parking (particularly relevant for Open week)?",
      "What's the check-in/check-out window?",
      "Are there any access restrictions (stairs, weight limits for period buildings)?",
    ]},
    { type: "h2", text: "My take" },
    { type: "p", text: "For a weekend break, a well-run Southport B&B beats a chain hotel at the same price point every time. You get a better breakfast, someone who'll point you toward the best pub for Sunday lunch, and the satisfaction of supporting an independent local business. That last bit matters to me." },
  ],

  "things-to-do-rainy-day-southport": [
    { type: "p", text: "It rains in Southport. I know, shocking for a seaside town in the north of England. The good news is that after 41 years here, I've got the rainy day plan locked in. The bad news is that 'it's raining, let's go to the beach anyway' is genuinely not the worst option — the beach in the rain has its own bleak charm. But if you'd rather stay dry, read on." },
    { type: "h2", text: "The Atkinson" },
    { type: "p", text: "The Atkinson on Lord Street is Southport's arts and culture centre — gallery, theatre, café, and museum all under one roof. It's genuinely excellent for a rainy afternoon. The current exhibitions rotate throughout the year, the café is a solid stop for lunch, and the building itself is worth looking at." },
    { type: "p", text: "They have regular events, screenings, comedy nights, and family activities. It's the kind of place that makes you proud to live somewhere. Check what's on before you visit — the programme changes and there's usually something worth seeing." },
    { type: "h2", text: "Silcock's Funland and the amusements" },
    { type: "p", text: "This is the old-school option and it absolutely delivers. Silcock's is a proper seaside amusement arcade — not the polished, sanitised kind, the real thing. Penny falls, grabber machines, kids losing their minds over 2p coins. If you've got children, budget £10 in coins and you'll buy yourself an hour of chaos that everyone secretly enjoys." },
    { type: "h2", text: "Wayfarers Arcade" },
    { type: "p", text: "The Victorian shopping arcade off Lord Street. It's covered, which is the main practical advantage on a wet day. But it's also genuinely beautiful — ornate ironwork, glass roof, independent shops. Even if you're not buying anything, it's worth walking through. One of those Southport things that visitors discover and locals take for granted." },
    { type: "h2", text: "Cinema" },
    { type: "p", text: "Southport has two options. Vue Cinema at Ocean Plaza for the big releases — standard multiplex, perfectly decent. The Southport Bijou Cinema is the more interesting choice — an independent cinema that shows classic films, hosts film clubs, and has the kind of atmosphere you don't get in a chain. I take my eldest there for proper film nights. Worth supporting." },
    { type: "h2", text: "Southport Market" },
    { type: "p", text: "Indoor, covered, and full of food stalls, independent traders, and regular events. Good for lunch, good for browsing, and the events programme includes live music and food festivals throughout the year. Perfect rainy afternoon material." },
    { type: "callout", emoji: "☔", text: "A rainy day in Southport isn't a ruined day. The Atkinson, the Arcade, and a long lunch covers it beautifully. Embrace the seaside greyness — it's part of the charm." },
    { type: "h2", text: "The honest advice" },
    { type: "p", text: "Dress for the weather and don't let it ruin the day. The best version of Southport in the rain is: morning at The Atkinson, lunch at Southport Market, afternoon in the arcade with the kids. That's a good day." },
  ],

  "southport-with-kids-full-guide": [
    { type: "p", text: "I have four children aged between eight and fifteen. I have been taking them to Southport's attractions since before they could walk. I know which toilets are clean, which car parks are close, which cafés have high chairs, and which 'family attractions' are actually just miserable. Here is the honest guide." },
    { type: "h2", text: "The beach — and what to actually bring" },
    { type: "p", text: "Southport beach is enormous. At low tide it stretches for miles. This is exciting for about twenty minutes and then you realise you've walked further than intended and the kids are tired and the tide is actually coming in. The trick is to stay closer to the pier end, which has more activity, easier parking, and less of the epic featureless flatness that starts to feel existential after a while." },
    { type: "ul", items: [
      "Bring proper shoes — the sand is wet, the ground is uneven near the dunes",
      "Check the tide times (genuinely — the tide goes out very far at Southport)",
      "The beach café near the Marine Lake is a solid pitstop",
      "Bring more cash than you think — rides, games, and ice cream add up fast"
    ]},
    { type: "h2", text: "Adventure Coast and the rides" },
    { type: "p", text: "Adventure Coast on Marine Drive has mini-golf, go-karts, and various other activities clustered together. It's well-run, the staff are good with kids, and the Viking Adventure Golf course is genuinely fun for all ages. My fifteen-year-old still likes it, which says something." },
    { type: "h2", text: "The amusements and funfair" },
    { type: "p", text: "Pleasureland and Silcock's Funland are the classic Southport amusement options. Pleasureland for outdoor rides in summer, Silcock's for the indoor arcade year-round. Budget accordingly. My kids are capable of spending twenty pounds in twenty minutes at Silcock's if left unsupervised. They are not unsupervised." },
    { type: "h2", text: "Eating out with children" },
    { type: "p", text: "Hickory's Smokehouse is the default family answer — big portions, kids' menu, reliably good. Southport Market is the flexible option when the children can't agree. For something quicker, the food options along the seafront do the job, though quality varies." },
    { type: "h2", text: "Day trip additions" },
    { type: "p", text: "Formby is 20 minutes south and has the Formby Squirrel Reserve (National Trust). Red squirrels, dunes, woodland paths. My youngest thinks it's the best place in the world. It's free for NT members and worth every penny for everyone else." },
    { type: "p", text: "Crosby Beach and the Anthony Gormley iron men ('Another Place') is a different kind of experience — more conceptual, a bit haunting, strangely beautiful. Good for older kids who can appreciate it. My thirteen-year-old was genuinely moved by it, which I did not expect." },
    { type: "callout", emoji: "🎡", text: "Summer school holidays are the busiest period for Southport's attractions. If you can visit mid-week, or in May/June before the main rush, you'll have a significantly better experience." },
  ],

  "southport-hidden-gems": [
    { type: "p", text: "It takes about a decade to properly know a town. After four decades in Southport, I'm still finding things I'd missed. These are the places that don't make it onto the tourist maps — the spots that locals mention in the kind of hushed tone that says 'don't tell everyone about this.'" },
    { type: "h2", text: "Churchtown — the village within the town" },
    { type: "p", text: "I live in Churchtown. I'm biased. But Churchtown is genuinely Southport's most underrated neighbourhood — a proper village feel, the Botanic Gardens, the Hesketh Arms, and the Swan restaurant. Most visitors never make it here. It's five minutes from the town centre by car. Go." },
    { type: "h2", text: "The Botanic Gardens" },
    { type: "p", text: "Free, beautiful, and almost always quiet. The Botanic Gardens in Churchtown have a lake, walking paths, a café, and glasshouses. On a weekday morning, you might almost have them to yourself. They're the kind of place that restores something in you when you've been staring at screens too long." },
    { type: "h2", text: "The backstreets of Birkdale village" },
    { type: "p", text: "Birkdale village is known for its proximity to Royal Birkdale golf course, but the village itself rewards a wander. There are independent shops, good cafés, and a residential character that feels distinct from the town centre. Less touristy, more genuinely local." },
    { type: "h2", text: "Marine Lake at dusk" },
    { type: "p", text: "Everyone goes to Marine Lake in the daytime. Fewer people go at dusk, when the light goes gold and the water reflects the sky and the whole thing looks like somewhere you'd use as a screensaver. Walking around the lake at that time of day is one of those small pleasures that Southport does genuinely well." },
    { type: "h2", text: "The covered Victorian market arcade" },
    { type: "p", text: "Wayfarers Arcade, off Lord Street. I've mentioned it in other posts. I'll keep mentioning it until everyone has been. It's one of the most beautiful indoor spaces in this part of England and most visitors walk past it without a second glance. The ironwork. The glass roof. The independent shops. Go in." },
    { type: "h2", text: "Crossens — the overlooked corner" },
    { type: "p", text: "Crossens is at the northern edge of Southport, heading toward the RSPB reserve at Marshside. It's not a tourist destination. It's a quiet residential area with a marshland backdrop that's genuinely striking in autumn. If you want to understand the landscape around Southport — the flatness, the big skies, the coastal marshes — a walk out toward Crossens does it better than anything else." },
    { type: "callout", emoji: "🗺️", text: "None of these places are secret in the grand scheme of things. They're just not on the main tourist trail. Which is exactly why they're worth finding." },
  ],

  "best-beaches-near-southport": [
    { type: "p", text: "Southport beach is famous. It's also one of the flattest, sandiest beaches in England — which is either a feature or a bug depending on what you're looking for. I'll give you the honest picture on Southport's beach and the alternatives nearby, so you can make your own call." },
    { type: "h2", text: "Southport main beach — the honest review" },
    { type: "p", text: "The beach at Southport stretches for miles and the sand is genuinely good. The catch is that the sea is far out — very far out at low tide. On a summer day, you might walk ten minutes to reach the water. On a spring tide, you might walk twenty. This surprises a lot of first-time visitors." },
    { type: "p", text: "That said, the beach is great for families with children who just want to run about, build sandcastles, and watch dogs terrorise seagulls. The pier area gives you the best of it — attractions, cafés, and enough activity to keep everyone interested." },
    { type: "h2", text: "Ainsdale — where locals actually go" },
    { type: "p", text: "Ainsdale beach is 10 minutes south of Southport by car. It's a bit wilder, a bit more natural, and a bit less developed. The dunes at Ainsdale are part of a nature reserve. The parking is easier. On a sunny weekend, this is where you'll find locals who know better than to compete with the tourist crowds at Southport's main beach." },
    { type: "h2", text: "Formby — squirrels, dunes, and the National Trust" },
    { type: "p", text: "Formby is 20 minutes south and it's genuinely special. The beach here is backed by massive sand dunes, pine woods, and the Formby Squirrel Reserve where you can see red squirrels — properly wild, not in cages. The National Trust manages it well. Parking fills up fast in summer; get there early." },
    { type: "h2", text: "Crosby — the iron men" },
    { type: "p", text: "Anthony Gormley's 'Another Place' at Crosby Beach is one of the most unusual and affecting public art installations in the country. One hundred cast iron figures, all based on Gormley's own body, looking out to sea. They've been there since 2005 and locals have stopped noticing them, which is a shame. If you haven't seen them, it's a 30-minute drive and absolutely worth it." },
    { type: "callout", emoji: "🌊", text: "Always check tide times at Southport beach before you visit. The tide goes out extremely far — and it comes back in faster than people expect. Especially worth knowing if you're walking toward the water with kids." },
    { type: "h2", text: "The quick answer" },
    { type: "p", text: "Southport for atmosphere and facilities. Ainsdale for a quieter, more natural experience. Formby for dunes, woods, and red squirrels. Crosby for Gormley's iron men. You could do all four in a weekend and you'd have done something genuinely worthwhile." },
  ],

  "royal-birkdale-guide-the-open": [
    { type: "p", text: "I'm not a golfer. Let me say that upfront. But I live five minutes from Royal Birkdale, I've watched The Open from the hillside before, and I know this corner of Southport better than most. This is the guide for people who want to go to The Open and do it properly — whether you're a dedicated golf fan or someone who's been dragged along by one." },
    { type: "h2", text: "About Royal Birkdale" },
    { type: "p", text: "Royal Birkdale Golf Club is consistently rated as one of the finest links courses in the world. It's hosted The Open 10 times before 2026, with previous champions including Arnold Palmer, Lee Trevino, Tom Watson, and Tiger Woods. The course is famous for its dramatic dunes, unpredictable wind, and fairways that run between the dunes rather than over them." },
    { type: "p", text: "The course is private — you can't just rock up and play. But during Open week, it becomes accessible in a way it never normally is. The spectator village, the grandstands, the atmosphere. It's worth experiencing even if you're neutral on golf." },
    { type: "h2", text: "Getting tickets" },
    { type: "p", text: "Tickets for The Open 2026 are sold through The R&A at theopen.com. Practice round tickets (Monday–Wednesday) are cheaper and often more available than championship round tickets. If you can only get practice round tickets, still go — you'll see the course, the players up close, and the atmosphere without the full-price crowds." },
    { type: "h2", text: "Getting there during Open week" },
    { type: "p", text: "Don't drive to the course. I cannot stress this enough. The park and ride shuttles from various points around Southport are the way to go. They're efficient, they drop you close, and you avoid the traffic that will make driving a misery." },
    { type: "ul", items: [
      "Park and ride shuttles from multiple locations — buy passes in advance",
      "Train to Birkdale station (Merseyrail) is a 15-minute walk from the course",
      "Southport town centre is a manageable 25-minute walk or short bus/taxi",
    ]},
    { type: "h2", text: "What to bring" },
    { type: "ul", items: [
      "Waterproofs — it's July on the Lancashire coast",
      "Comfortable shoes — the course is large and you'll walk miles",
      "Cash — some hospitality areas are cash-only",
      "Binoculars — the grandstands are good but binoculars help",
    ]},
    { type: "h2", text: "Where to eat and drink near the course" },
    { type: "p", text: "There's a substantial hospitality village on site during Open week. Outside the course, Birkdale village is your best bet for food and drink. The Bold Hotel does Open week packages. Book everything well in advance — this is not a normal week in Southport." },
    { type: "callout", emoji: "⛳", text: "The Open at Royal Birkdale is, in my experience, one of those events that's better than you expect even if you're not a golf fan. The atmosphere, the proximity to world-class sport, the Southport setting. It's a special week." },
  ],

  "best-golf-courses-southport": [
    { type: "p", text: "Southport sits at the heart of one of England's greatest stretches of links golf. Within 30 minutes of the town, you have Royal Birkdale, Hillside, Southport & Ainsdale, Formby, and a handful of other courses. If you play golf and you haven't made a trip to this corner of Lancashire, something has gone wrong in your planning." },
    { type: "h2", text: "Royal Birkdale" },
    { type: "p", text: "The obvious one. Royal Birkdale is a world-class links course and an Open Championship venue. Getting a tee time here as a visitor is genuinely difficult — the club is private and protects its course. But it's not impossible. Contact the club directly, book well in advance, and be prepared to pay premium green fees. Worth every penny if you get on." },
    { type: "h2", text: "Hillside Golf Club" },
    { type: "p", text: "Hillside is next door to Royal Birkdale — literally adjacent, sharing the same dune landscape. It's been called the 'hidden gem' of Lancashire golf, which understates it. Hillside is a championship-standard links course that many golfers rate as highly as Birkdale itself. Slightly more accessible for visitors, and the green fees reflect that." },
    { type: "h2", text: "Southport & Ainsdale" },
    { type: "p", text: "S&A has its own proud history — it's hosted the Ryder Cup twice, in 1933 and 1937. The course sits in a natural dune setting between Southport and Ainsdale. More welcoming to visiting golfers than some of the higher-profile clubs, with consistently strong reviews. Good clubhouse, good course." },
    { type: "h2", text: "Formby Golf Club" },
    { type: "p", text: "Formby is 20 minutes south of Southport and has three courses — the main men's course, the ladies' course (one of the best women's golf facilities in the country), and Formby Hall. The main course is beautiful links golf through pines and dunes. A proper day out." },
    { type: "h2", text: "Practical notes for visiting golfers" },
    { type: "ul", items: [
      "Book well in advance — the best courses fill up months ahead, especially in summer",
      "Handicap certificates are required at most clubs",
      "Smart casual dress code is standard — check individual club rules before you go",
      "The area gets busy during Open week — either embrace it or avoid it",
    ]},
    { type: "callout", emoji: "⛳", text: "The Lancashire Links stretch — from Formby up through Southport to Lytham — is as good as links golf gets in England. If golf is your thing, a dedicated long weekend here deserves a place on your bucket list." },
  ],

  "best-independent-shops-lord-street": [
    { type: "p", text: "Lord Street is one of the great Victorian boulevards of England. People from outside Southport are often genuinely surprised when they see it for the first time — the width of it, the tree canopies, the covered walkways. Napoleon III supposedly used it as inspiration for the Champs-Élysées. Whether that's true or not, it makes a good story, and the street lives up to it." },
    { type: "h2", text: "Wayfarers Arcade" },
    { type: "p", text: "The Victorian arcade off Lord Street is the first stop. Ornate ironwork, glass roof, independent traders selling jewellery, antiques, clothing, and collectibles. It's the kind of place you can browse for an hour without intending to buy anything and leave with something you didn't know you needed. There's always something surprising in here." },
    { type: "h2", text: "Independent fashion and boutiques" },
    { type: "p", text: "Lord Street has a genuine mix of independents alongside the chains. The covered sections have a concentration of clothing boutiques — the kind of places that get new stock regularly and have an actual buyer making decisions, rather than a central buying team in a head office. Worth a browse if you're after something you won't find on every high street." },
    { type: "h2", text: "Food shops and delis" },
    { type: "p", text: "There are a handful of independent food shops and delis within easy reach of Lord Street. Good for local produce, gifts, and the kind of specialist stock you can't get in Tesco. Worth hunting out if food shopping is your version of retail therapy. Southport's independent food scene is stronger than its size would suggest." },
    { type: "h2", text: "Galleries and gifts" },
    { type: "p", text: "The Atkinson on Lord Street has a gallery shop attached. There are also a couple of independent galleries selling local artwork — prints, photography, ceramics. Good for gifts that have some connection to the place rather than being generic tourist tat." },
    { type: "h2", text: "The charity shop circuit" },
    { type: "p", text: "This is the underrated one. Southport's charity shops punch above their weight. There are several along and adjacent to Lord Street, and they get good quality donations because of the demographics of the town. If you're a vintage or second-hand shopper, factor in an hour. You won't always find something, but when you do it's worth it." },
    { type: "callout", emoji: "🛍️", text: "Best time to visit: weekday mornings in spring and autumn. Avoid bank holiday weekends when Lord Street gets extremely busy and parking becomes a competitive sport." },
  ],

  "best-bars-southport-lord-street": [
    { type: "p", text: "I don't go out as much as I used to. Four kids will do that. But when I do, I know where I'm going. Southport's bar scene isn't Manchester or Liverpool, and it shouldn't try to be. What it is, when it's at its best, is proper local pubs and bars with character, decent drinks, and the kind of atmosphere that comes from people who actually live here." },
    { type: "h2", text: "Coopers Bar" },
    { type: "p", text: "My first port of call, every time. Coopers is a family-run independent bar that does jazz on Sundays, live rock and acoustic acts on Fridays and Saturdays, and open mic on Sunday evenings. It's been a Southport institution for years. Not flashy, not trying to be anything it isn't. Just a genuinely good bar with consistently good music and a crowd that's there for the right reasons." },
    { type: "h2", text: "Along the Lord Street stretch" },
    { type: "p", text: "Lord Street has a decent range of bars at the southern end in particular. The mix changes year to year — new places open, some don't last — but the core of independent and small-chain bars along that stretch makes for a good starting point for an evening out." },
    { type: "h2", text: "The Hesketh Arms, Churchtown" },
    { type: "p", text: "Not technically Lord Street, but worth the short journey. Real ale, proper pub atmosphere, regular live music. If you want a 'Southport local' experience rather than a 'bar on a main street' experience, the Hesketh delivers it." },
    { type: "h2", text: "What Southport nightlife actually looks like" },
    { type: "p", text: "Southport has a town centre late-night scene that's livelier than you might expect for a seaside resort. Banff is the main nightclub option for those who want that. But the most enjoyable nights here tend to be in the pubs and bars that have live music — there's a genuinely active live music scene across multiple venues." },
    { type: "ul", items: [
      "The Auld Dubliner — traditional Irish pub with regular live acts",
      "The Ship and Anchor — old-school rock pub with Friday and Saturday bands",
      "Avenue Southport — central spot with acoustic acts",
      "Kokomo — neighbourhood bar with live music Thursday to Sunday",
    ]},
    { type: "callout", emoji: "🎶", text: "Check the Southport Live Music Facebook page before you visit — it's the best single source for what's happening on any given weekend. Good for planning a night where you follow the music rather than committing to one venue." },
    { type: "h2", text: "The honest verdict" },
    { type: "p", text: "Southport's best nights are in its live music pubs. Coopers on a Friday. The Hesketh on a Sunday. The Ship and Anchor on a weekend. That's a better night out than trying to replicate what you'd get in a bigger city. Know what Southport does well, and enjoy it." },
  ],

  "best-spas-southport": [
    { type: "p", text: "My wife sends me to the spa occasionally. I go under protest and then spend the entire time wondering why I don't do this more often. Southport has a growing wellness offering — between the hotel spas and the independent studios, there's enough to fill a proper spa day without driving to Manchester." },
    { type: "h2", text: "Hotel spa options" },
    { type: "p", text: "The Grand and the Bold Hotel both have spa and wellness facilities. The Grand's offering is more traditional — treatments, steam room, the kind of environment that feels appropriately indulgent. The Bold has a more boutique feel, which suits its hotel aesthetic." },
    { type: "p", text: "Both are worth calling ahead to book, especially for popular weekend slots. They fill up for hen parties and birthday spa days, so spontaneity isn't always rewarded." },
    { type: "h2", text: "Independent day spas" },
    { type: "p", text: "Southport has a good number of independent beauty studios and spa rooms that offer day spa experiences at better value than the hotels. The quality varies, but the best ones are genuinely good — trained therapists, proper treatment rooms, and the kind of care that a small business brings when its reputation depends on it." },
    { type: "h2", text: "What Southport's wellness scene does well" },
    { type: "p", text: "There's a growing number of yoga studios, pilates classes, and wellness practitioners that have established themselves in Southport over the last few years. The market for wellness services has expanded as the town's demographics have shifted. For a coastal town of this size, the offer is solid." },
    { type: "h2", text: "Booking tips" },
    { type: "ul", items: [
      "Book at least a week in advance for weekend slots",
      "Ask specifically about what's included — not all 'spa days' include the same amenities",
      "Check whether the spa has a pool or hydrotherapy facilities if that matters to you",
      "For couples' treatments, availability is more limited — book early",
    ]},
    { type: "callout", emoji: "💆", text: "If you're visiting for a special occasion — birthday, anniversary, a break from the kids — a spa day in Southport makes for a complete and reasonably priced day out without leaving the town." },
  ],

  "marine-lake-water-sports-southport": [
    { type: "p", text: "Marine Lake is one of the UK's largest man-made marine lakes. It sits right in the heart of Southport's seafront. And somehow, despite being large, beautiful, and right there, it's underused by the majority of visitors who come here. This is about to change with MLEC opening in 2027, but right now it's a genuinely underrated gem." },
    { type: "h2", text: "What's available on the lake" },
    { type: "p", text: "West Lancashire Yacht Club operates from the lake and offers sailing lessons and taster sessions to non-members. The club is one of the most active sailing clubs in the region — the annual 24-hour Dinghy Race every September is a genuinely spectacular event." },
    { type: "ul", items: [
      "Sailing — lessons and club sessions via West Lancashire Yacht Club",
      "Kayaking and paddleboarding — available through local providers seasonally",
      "Model boating — the lake has a dedicated area for remote-controlled boats",
      "Pedalos and rowing boats — seasonal, family-friendly option",
    ]},
    { type: "h2", text: "Adventure Coast" },
    { type: "p", text: "Adventure Coast on Marine Drive overlooks the lake and has Viking Adventure Golf (genuinely well-designed, not the tired crazy golf you're imagining), go-karts, and various activity options. Good for families who want structured activity rather than open-water stuff." },
    { type: "h2", text: "Kids on the lake" },
    { type: "p", text: "The paddling and shallow areas near the promenade are safe for young children on calm days. The main sailing area is for properly supervised activities. If you've got kids who've never been on the water before, a sailing taster session at West Lancashire Yacht Club is a genuinely good experience and surprisingly affordable." },
    { type: "h2", text: "The MLEC effect" },
    { type: "p", text: "When the Marine Lake Events Centre opens in 2027, this whole area of the seafront is going to transform. The lake will be the centrepiece of a major entertainment and culture destination. Right now, you've got the lake and relative peace. In 2027, you'll have the lake plus 515,000 additional visitors a year. Worth making the most of the current quiet." },
    { type: "callout", emoji: "⛵", text: "The West Lancashire Yacht Club 24-hour Dinghy Race (September) is one of the most underrated spectator events in Southport. Over 500 competitors, coloured sails on the lake, free to watch. Put it in the diary." },
  ],

  "parking-guide-southport": [
    { type: "p", text: "Parking in Southport isn't as bad as people think. I say this as someone who lives here and has spent the better part of four decades occasionally circling car parks. The town has plenty of options — the trick is knowing which ones to use and when." },
    { type: "h2", text: "Town centre car parks" },
    { type: "p", text: "The main town centre car parks are clustered around Lord Street and the Market area. They fill up on weekends, but there's usually something available if you're patient and know where to look. The multi-storey options tend to have more availability than the surface car parks, and they're usually fairly central." },
    { type: "ul", items: [
      "Lord Street car park — central, convenient, busy on weekends",
      "Market Street multi-storey — slightly less well-known, often has spaces when others are full",
      "Ocean Plaza — if you're visiting the seafront and don't mind a short walk",
    ]},
    { type: "h2", text: "Seafront parking" },
    { type: "p", text: "Marine Drive along the seafront has parking with sea views. It's popular in summer and can fill up by mid-morning on a good weather day. The advantage is that you're already at the beach when you park. Worth the early arrival if that's your plan." },
    { type: "h2", text: "Free parking — yes, it exists" },
    { type: "p", text: "There is residential parking on the outskirts of the town centre that's free for a limited period. Some of the residential streets near the edge of the shopping area have unrestricted parking for 30–60 minutes. Worth knowing if you're popping in quickly. Not worth attempting for a full day." },
    { type: "h2", text: "During events" },
    { type: "p", text: "During The Open Championship, the Flower Show, the Air Show, and the Comedy Festival, parking in Southport gets dramatically more complicated. Use the park and ride where it's available. Don't try to drive to Royal Birkdale or Victoria Park during these events — it's not worth the stress." },
    { type: "callout", emoji: "📱", text: "The RingGo app works across most Southport car parks and saves you carrying coins. Worth setting up before you visit. Some car parks also accept contactless payment directly at the machine now." },
    { type: "h2", text: "The honest picture" },
    { type: "p", text: "Southport is not a city. Parking is manageable with a bit of planning. The issues tend to arise on sunny summer weekends and during major events — both of which are predictable. Plan for them, and you'll be fine." },
  ],

  "perfect-weekend-southport": [
    { type: "p", text: "People ask me what to do in Southport all the time. I live here. I've thought about it. Here's the definitive plan for a weekend that makes the most of what this town actually does well — no padding, no tourist board nonsense. Two days, done properly." },
    { type: "h2", text: "Friday evening" },
    { type: "p", text: "Arrive, drop your bags, and go straight to dinner. Don't faff about. If you've booked well, The Swan in Churchtown or Volare on Lord Street will do it. If you're more spontaneous, walk down Lord Street and see what's on. Get a proper meal, have a drink, and get your bearings. Southport's best first impression is on foot on Lord Street on a Friday evening." },
    { type: "h2", text: "Saturday morning" },
    { type: "p", text: "Coffee first. There are good independent cafés on and around Lord Street and in Birkdale village. After coffee, go to Churchtown. Walk around the Botanic Gardens — it's free, it takes about an hour at a comfortable pace, and it's one of the loveliest places in Southport. Have a look at Churchtown village itself while you're there. The Hesketh Arms does a solid lunch if you're staying in the area." },
    { type: "h2", text: "Saturday afternoon" },
    { type: "p", text: "Beach. Specifically the pier area. Walk out on Southport Pier — it's the second longest in England and the views back toward the town from the end of it are genuinely good. Check the tide times before you go if you want to walk on the sand. The Marine Lake area is good for an afternoon wander if the weather's decent." },
    { type: "p", text: "If you have kids with you, the amusements and Adventure Golf will absorb the afternoon perfectly. If you don't, the beach, the pier, and a wander through Wayfarers Arcade covers it beautifully." },
    { type: "h2", text: "Saturday evening" },
    { type: "p", text: "Dinner, then a proper pub or bar. Coopers Bar on a Saturday has live music that's consistently good. The Hesketh Arms has a warm, local atmosphere. End the night however feels right — Southport rewards people who settle in rather than rushing." },
    { type: "h2", text: "Sunday morning" },
    { type: "p", text: "Southport Market on a Sunday morning is underrated. Food stalls, independent sellers, occasional live music. It's a good loose structure for a Sunday when you don't want to commit to a plan. Alternatively, The Atkinson often has something on at weekends." },
    { type: "h2", text: "Sunday afternoon — extend or head home" },
    { type: "p", text: "If you're extending, Formby is 20 minutes south — squirrels, dunes, and a proper coastal walk. Crosby is 30 minutes — the Gormley iron men. If you're heading home, you've had a genuinely good weekend. That's the honest version of Southport at its best." },
    { type: "callout", emoji: "📅", text: "This itinerary works in most seasons. Summer gives you the beach at its best. Spring and autumn give you the town without the crowds. Winter gives you the Atkinson, the pubs, and a quieter version of everything that's still worth having." },
  ],

  "southport-events-guide-2026": [
    { type: "p", text: "I've lived in Southport long enough to know that 2026 is different. It's genuinely the biggest year this town has had in decades. Two world-class events within 12 months, several brand-new events added to the calendar, and the beginning of the MLEC era. Here's what you need to know." },
    { type: "h2", text: "The Open Championship — July 12–19" },
    { type: "p", text: "Royal Birkdale hosts the 154th Open Championship in July. This is the biggest event in Southport's sporting history. The best golfers in the world will be here for a week. Accommodation is almost gone. Tickets are available through The R&A. If you're planning to come for this, act now — I cannot say that emphatically enough." },
    { type: "h2", text: "Lightport — February 14–16 (already happened, worth knowing for next year)" },
    { type: "p", text: "The brand-new light installation on Lord Street from Lucid Creates was outstanding — the kind of event that Southport didn't used to have but absolutely should. 7,000 luminous pixels forming a rainbow above Lord Street, water projections, four zones of immersive light art. It ran for three evenings and the turnout was impressive. Worth keeping an eye on for 2027." },
    { type: "h2", text: "Cristal Palace — April 3–4" },
    { type: "p", text: "French street theatre company Transe Express brings their spectacular Cristal Palace show to Lord Street. A 15-metre flying chandelier, aerial dancers, live musicians. This is the kind of event that transforms a street into something genuinely magical. Free to attend. Get there early." },
    { type: "h2", text: "Big Top Festival — May 2–3" },
    { type: "p", text: "Contemporary circus comes to Southport — world-class companies including Circa and Gandini Juggling performing across outdoor stages. Free to attend. Workshops, acrobatics, live music. A proper festival atmosphere that's accessible for all ages." },
    { type: "h2", text: "Food & Drink Festival — May 29–31" },
    { type: "p", text: "The Food and Drink Festival is a Southport institution. Street food, local producers, artisan cheeses, live music, and three days of eating and drinking well. One of the better food festivals in the North West. Free to enter." },
    { type: "h2", text: "Southport Air Show — August 29–30" },
    { type: "p", text: "The Air Show is back. Always a highlight of the summer — the Red Arrows, display teams, aerobatics over the beach. It draws enormous crowds for good reason. Free to attend from the beach, with paid grandstand options." },
    { type: "h2", text: "Comedy Festival — October 2–18" },
    { type: "p", text: "The Southport Comedy Festival runs for almost three weeks every October and has become one of the best in the country. 2026 features Henning Wehn, Gary Delaney, and more to be announced. Tickets sell fast for the headliners. The heated marquee in Victoria Park is a brilliant setting." },
    { type: "callout", emoji: "📅", text: "For the full 2026 events calendar with dates, venues, and ticket links, visit southportguide.co.uk/events. We update it regularly as new events are confirmed." },
    { type: "h2", text: "The bigger picture" },
    { type: "p", text: "2026 is the year Southport starts to properly announce itself. The Open brings global attention. The new events — Lightport, Cristal Palace, Big Top — signal a town with cultural ambition. And in the background, the MLEC is taking shape ready for 2027. If you've been meaning to visit Southport, this is the year to do it." },
  ],

};
